[package]
name = "envoy-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
envoy-control-plane = {version = "0.4.0", features = ["grpc"]}
futures = "0.3"
json = "0.12.4"
prost = "0.9"
tokio = {version = "1" , features = ["rt-multi-thread", "macros"]}
tonic = "0.6.2"
