[package]
name = "envoy-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
prost = "0.9"
prost-types = "0.9"
tokio = {version = "1" , features = ["rt-multi-thread", "macros"]}
tonic = "0.6.2"

[build-dependencies]
tonic-build = "0.6.2"
